Use #width and #heght instead of #size
It fixes following error:

    lib/rabbit/renderer/display/base.rb:140:in `set_drawable': undefined method `size' for #<#<Class:0x00000005395170>:0x53950d0 ptr=0x19065a0>